name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Run Tests
      run: mvn test

    - name: Check and Create Tag
      if: github.ref == 'refs/heads/main' && success()
      run: |
        # Generate a JAR file
        mvn clean package

        # Get the current project version from the POM.xml
        PROJECT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)

        # Increment the project version (e.g., 1.0.0 -> 1.0.1)
        NEW_VERSION="${PROJECT_VERSION%.*}.$((${PROJECT_VERSION##*.}+1))"
        
        # Update the project version in the POM.xml
        mvn versions:set -DnewVersion=${NEW_VERSION} -DgenerateBackupPoms=false

        # Commit the updated POM.xml
        git commit -am "Bump version to ${NEW_VERSION}"

        # Create a version tag and push it
        git tag -a v${NEW_VERSION} -m "Version ${NEW_VERSION}"
        git push --tags

    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
